/*
 * GreenFlash.cpp
 *
 *  Created on: 12 апр. 2022 г.
 *      Author: layst
 */

#include "GreenFlash.h"
#include "Settings.h"
#include "buzzer.h"
#include "kl_lib.h"
#include "adcF072.h"
#include "shell.h"
#include "MsgQ.h"
#include "EvtMsgIDs.h"

static TmrKL_t ITmr {999, evtIdDelayEnd, tktOneShot}; // Delay is dummy
static virtual_timer_t FlashTmr;
//uint16_t DacValue;
bool IsOn = false;
static enum {staCharging, staReady, staWaitingBtnPress, staBeforeFlash, staDelayBeforeRestart} State;

//void SetDac(uint16_t v) { DAC->DHR12R1 = v; }

void FlashCallbackI(virtual_timer_t *vtp, void *p) {
    chSysLockFromISR();
    IsOn = false;
//    SetDac(0);
    PinSetLo(GREEN_LED);
    EvtQMain.SendNowOrExitI(EvtMsg_t(evtIdFlashEnd));
    chSysUnlockFromISR();
}

void Fire() {
    Printf("Fire\r");
//    DacValue = LED_DAC_START;
//    SetDac(DacValue);
    PinSetHi(GREEN_LED);
    IsOn = true;
    Buzzer.Off();
    chVTSet(&FlashTmr, TIME_MS2I(Settings.FlashDurtn_ms), FlashCallbackI, nullptr);
}

void EnterDelayBeforeRestart() {
    State = staDelayBeforeRestart;
    Buzzer.SetVolume(Settings.Volume.BeforeRestart);
    Buzzer.BeWaitingRestart();
    // Start DelayBeforeRestart timeout. Will end immediately if 0.
    ITmr.StartOrRestart(TIME_S2I(Settings.Delay.BeforeRestart.Value));
}

void EnterCharging() {
//    Settings.Load();
    Buzzer.SetVolume(Settings.Volume.Charging);
    Buzzer.BuzzUp();
    State = staCharging;
    ITmr.Stop(); // End event generated by buzzer
}

void EnterReady() {
    State = staReady;
    Buzzer.SetVolume(Settings.Volume.Ready);
    Buzzer.BeReady();
    // Start Ready2Press timeout. Will end immediately if 0.
    ITmr.StartOrRestart(TIME_S2I(Settings.Delay.Ready2Press));
}

namespace GreenFlash {

void Init() {
    PinSetupOut(GREEN_LED, omPushPull, psHigh);
    // Set initial state
    if(Settings.Delay.Start2Ready == 0) EnterReady();
    else EnterCharging();
}

void OnDelayEnd() {
//    Printf("DE: %u\r", State);
    switch(State) {
        case staCharging: EnterReady(); break; // End event generated by buzzer, not timer, but who cares

        case staReady:
            State = staWaitingBtnPress;
            Buzzer.SetVolume(Settings.Volume.WaitingBtn);
            Buzzer.BeReady();
            // Start OffIfNotFired timeout if not 0. If 0 - do not start and wait forever.
            if(Settings.Delay.OffIfNotFired != 0) ITmr.StartOrRestart(TIME_S2I(Settings.Delay.OffIfNotFired));
            break;

        case staWaitingBtnPress: EnterDelayBeforeRestart(); break; // NotFired timeout occured
        case staBeforeFlash: Fire(); break; // Time to fire
        case staDelayBeforeRestart: EnterCharging(); break;  // Delay ended
    } // switch
}

void OnFlashEnd() {
    EnterDelayBeforeRestart();
}

void OnBtnPress() {
    if(State == staWaitingBtnPress) {
        State = staBeforeFlash;
        Buzzer.SetVolume(Settings.Volume.BeforeFlash);
        Buzzer.BeReady();
        // Start BeforeFlash timeout. Will end immediately if 0.
        ITmr.StartOrRestart(TIME_S2I(Settings.Delay.BeforeFlash));
    }
}

} // namespace
